"""
Django settings for footwear project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import parse_qs, unquote, urlparse

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
DEPLOYMENT_ENV = os.environ.get("DJANGO_ENV", "development").strip().lower()
IS_PRODUCTION = DEPLOYMENT_ENV == "production"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if IS_PRODUCTION:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set in production.")
    SECRET_KEY = "local-only-insecure-development-key-change-before-deploy"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "true").strip().lower() in {"1", "true", "yes", "on"}
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured("DJANGO_DEBUG must be false in production.")

ALLOWED_HOSTS = [host.strip() for host in os.environ.get(
    "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,[::1]"
).split(",") if host.strip()]
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("DJANGO_ALLOWED_HOSTS must contain the production host.")
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.environ.get(
    "DJANGO_CSRF_TRUSTED_ORIGINS", ""
).split(",") if origin.strip()]
if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',

    'accounts',
    'products',
    'orders',
    'dashboard',
    'shops',
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "dashboard.middleware.StaffActionAuditMiddleware",
]

ROOT_URLCONF = "footwear.urls"

BASE_DIR = Path(__file__).resolve().parent.parent

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shops.context_processors.language_context',
            ],
        },
    },
]

WSGI_APPLICATION = "footwear.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get("DJANGO_DATABASE_URL", "").strip()
if DATABASE_URL:
    parsed_database_url = urlparse(DATABASE_URL)
    if parsed_database_url.scheme in {"postgres", "postgresql", "postgresql+psycopg"}:
        database_options = parse_qs(parsed_database_url.query)
        DATABASES = {"default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": unquote(parsed_database_url.path.lstrip("/")),
            "USER": unquote(parsed_database_url.username or ""),
            "PASSWORD": unquote(parsed_database_url.password or ""),
            "HOST": parsed_database_url.hostname or "",
            "PORT": parsed_database_url.port or "",
            "CONN_MAX_AGE": 600,
            "OPTIONS": {key: values[-1] for key, values in database_options.items()},
        }}
        if IS_PRODUCTION and "sslmode" not in DATABASES["default"]["OPTIONS"]:
            DATABASES["default"]["OPTIONS"]["sslmode"] = "require"
    elif parsed_database_url.scheme == "sqlite":
        DATABASES = {"default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": unquote(parsed_database_url.path),
        }}
    else:
        raise ImproperlyConfigured("DJANGO_DATABASE_URL must use PostgreSQL or SQLite.")
elif IS_PRODUCTION:
    raise ImproperlyConfigured("DJANGO_DATABASE_URL must point to production PostgreSQL.")
else:
    DATABASES = {"default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_DELIVERY_FEE = '50.00'
DEFAULT_DELIVERY_MIN_DAYS = int(os.environ.get('DEFAULT_DELIVERY_MIN_DAYS', '1'))
DEFAULT_DELIVERY_MAX_DAYS = int(os.environ.get('DEFAULT_DELIVERY_MAX_DAYS', '3'))
RETURN_WINDOW_DAYS = 7

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'true').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Jaunpur Footwear <noreply@example.com>')
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID', '')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET', '')
RAZORPAY_WEBHOOK_SECRET = os.environ.get('RAZORPAY_WEBHOOK_SECRET', '')
WHATSAPP_GRAPH_API_VERSION = os.environ.get('WHATSAPP_GRAPH_API_VERSION', '')
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_ACCESS_TOKEN = os.environ.get('WHATSAPP_ACCESS_TOKEN', '')
WHATSAPP_ORDER_TEMPLATE = os.environ.get('WHATSAPP_ORDER_TEMPLATE', '')
MARKETPLACE_TOKEN_ENCRYPTION_KEY = os.environ.get('MARKETPLACE_TOKEN_ENCRYPTION_KEY', '')
FLIPKART_CLIENT_ID = os.environ.get('FLIPKART_CLIENT_ID', '')
FLIPKART_CLIENT_SECRET = os.environ.get('FLIPKART_CLIENT_SECRET', '')
FLIPKART_REDIRECT_URI = os.environ.get('FLIPKART_REDIRECT_URI', '')
FLIPKART_AUTHORIZATION_URL = os.environ.get('FLIPKART_AUTHORIZATION_URL', 'https://seller.flipkart.com/oauth/authorize')
FLIPKART_TOKEN_URL = os.environ.get('FLIPKART_TOKEN_URL', 'https://api.flipkart.net/oauth-service/oauth/token')
FLIPKART_API_BASE_URL = os.environ.get('FLIPKART_API_BASE_URL', 'https://api.flipkart.net/sellers')
AMAZON_APPLICATION_ID = os.environ.get('AMAZON_APPLICATION_ID', '')
AMAZON_LWA_CLIENT_ID = os.environ.get('AMAZON_LWA_CLIENT_ID', '')
AMAZON_LWA_CLIENT_SECRET = os.environ.get('AMAZON_LWA_CLIENT_SECRET', '')
AMAZON_REDIRECT_URI = os.environ.get('AMAZON_REDIRECT_URI', '')
AMAZON_AUTHORIZATION_URL = os.environ.get('AMAZON_AUTHORIZATION_URL', 'https://sellercentral.amazon.in/apps/authorize/consent')
AMAZON_OAUTH_VERSION = os.environ.get('AMAZON_OAUTH_VERSION', '')
AMAZON_LWA_TOKEN_URL = os.environ.get('AMAZON_LWA_TOKEN_URL', 'https://api.amazon.com/auth/o2/token')
AMAZON_SP_API_ENDPOINT = os.environ.get('AMAZON_SP_API_ENDPOINT', 'https://sellingpartnerapi-eu.amazon.com')
MARKETPLACE_API_USER_AGENT = os.environ.get('MARKETPLACE_API_USER_AGENT', 'JaunpurFootwear/1.0 (Language=Python)')
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', '')
if IS_PRODUCTION and not CELERY_BROKER_URL:
    raise ImproperlyConfigured("CELERY_BROKER_URL is required in production.")
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TIME_LIMIT = 300
CELERY_TASK_SOFT_TIME_LIMIT = 270
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULE = {
    "authorized-marketplace-sync-every-30-minutes": {
        "task": "orders.tasks.sync_marketplace_channels_task",
        "schedule": 1800.0,
    },
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticatedOrReadOnly"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "{asctime} {levelname} {name}: {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {"handlers": ["console"], "level": os.environ.get("DJANGO_LOG_LEVEL", "INFO")},
    "loggers": {
        "django.request": {"handlers": ["console"], "level": "WARNING", "propagate": False},
        "orders": {"handlers": ["console"], "level": "INFO", "propagate": False},
        "shops": {"handlers": ["console"], "level": "INFO", "propagate": False},
    },
}

MEDIA_STORAGE_BACKEND = os.environ.get(
    "DJANGO_MEDIA_STORAGE", "s3" if IS_PRODUCTION else "local"
).strip().lower()
if MEDIA_STORAGE_BACKEND == "s3":
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME", "")
    if IS_PRODUCTION and not AWS_STORAGE_BUCKET_NAME:
        raise ImproperlyConfigured("AWS_STORAGE_BUCKET_NAME is required for production media storage.")
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "") or None
    AWS_S3_ENDPOINT_URL = os.environ.get("AWS_S3_ENDPOINT_URL", "") or None
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_OBJECT_PARAMETERS = {"CacheControl": "max-age=86400"}
    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3.S3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }
elif MEDIA_STORAGE_BACKEND != "local":
    raise ImproperlyConfigured("DJANGO_MEDIA_STORAGE must be 'local' or 's3'.")
